/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Division = IDL.Variant({
  'softballMinors' : IDL.Null,
  'baseballMinors' : IDL.Null,
  'softballMajors' : IDL.Null,
  'softballCoachPitch' : IDL.Null,
  'baseballCoachPitch' : IDL.Null,
  'baseballMajors' : IDL.Null,
  'coEdTeeBall' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MvpInfo = IDL.Record({
  'name' : IDL.Text,
  'team' : IDL.Text,
  'photo' : ExternalBlob,
});
export const GameRecord = IDL.Record({
  'homeTeam' : IDL.Text,
  'date' : IDL.Text,
  'division' : Division,
  'mvpInfo' : IDL.Opt(MvpInfo),
  'homeScore' : IDL.Nat,
  'awayTeam' : IDL.Text,
  'awayScore' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGame' : IDL.Func([GameRecord], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExternalMvpPhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  'deleteGame' : IDL.Func([IDL.Nat], [], []),
  'getAllGames' : IDL.Func([], [IDL.Vec(GameRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGame' : IDL.Func([IDL.Nat], [GameRecord], ['query']),
  'getGamesByDivision' : IDL.Func([Division], [IDL.Vec(GameRecord)], ['query']),
  'getMvpPhotoByGameId' : IDL.Func([IDL.Nat], [ExternalBlob], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGame' : IDL.Func([IDL.Nat, GameRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Division = IDL.Variant({
    'softballMinors' : IDL.Null,
    'baseballMinors' : IDL.Null,
    'softballMajors' : IDL.Null,
    'softballCoachPitch' : IDL.Null,
    'baseballCoachPitch' : IDL.Null,
    'baseballMajors' : IDL.Null,
    'coEdTeeBall' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MvpInfo = IDL.Record({
    'name' : IDL.Text,
    'team' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const GameRecord = IDL.Record({
    'homeTeam' : IDL.Text,
    'date' : IDL.Text,
    'division' : Division,
    'mvpInfo' : IDL.Opt(MvpInfo),
    'homeScore' : IDL.Nat,
    'awayTeam' : IDL.Text,
    'awayScore' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGame' : IDL.Func([GameRecord], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExternalMvpPhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
    'deleteGame' : IDL.Func([IDL.Nat], [], []),
    'getAllGames' : IDL.Func([], [IDL.Vec(GameRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGame' : IDL.Func([IDL.Nat], [GameRecord], ['query']),
    'getGamesByDivision' : IDL.Func(
        [Division],
        [IDL.Vec(GameRecord)],
        ['query'],
      ),
    'getMvpPhotoByGameId' : IDL.Func([IDL.Nat], [ExternalBlob], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGame' : IDL.Func([IDL.Nat, GameRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };