/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Division = { 'softballMinors' : null } |
  { 'baseballMinors' : null } |
  { 'softballMajors' : null } |
  { 'softballCoachPitch' : null } |
  { 'baseballCoachPitch' : null } |
  { 'baseballMajors' : null } |
  { 'coEdTeeBall' : null };
export type ExternalBlob = Uint8Array;
export interface GameRecord {
  'homeTeam' : string,
  'date' : string,
  'division' : Division,
  'mvpInfo' : [] | [MvpInfo],
  'homeScore' : bigint,
  'awayTeam' : string,
  'awayScore' : bigint,
}
export interface MvpInfo {
  'name' : string,
  'team' : string,
  'photo' : ExternalBlob,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / --- Game Management ---
   */
  'addGame' : ActorMethod<[GameRecord], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / --- MVP Photo Management ---
   */
  'createExternalMvpPhoto' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'deleteGame' : ActorMethod<[bigint], undefined>,
  'getAllGames' : ActorMethod<[], Array<GameRecord>>,
  /**
   * / --- User Profile Management ---
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / --- Query Functions (Public Read Access) ---
   */
  'getGame' : ActorMethod<[bigint], GameRecord>,
  'getGamesByDivision' : ActorMethod<[Division], Array<GameRecord>>,
  'getMvpPhotoByGameId' : ActorMethod<[bigint], ExternalBlob>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGame' : ActorMethod<[bigint, GameRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];